### PR TITLE
Precommits run inside node (web) container

### PR DESCRIPTION
**Pull request by rynocouse**
Run lint-staged inside node container

### CODE REVIEW

**Comment by unruffledBeaver** [comment]
We should also consider that if we force docker in development are we breaking our one-to-one if we end up deploying the app as a static in production? We currently have an issue open to implement static builds, #11. Is that no longer valid after this merge?

**Comment by stevescavo** [comment]
> We should also consider that if we force docker in development are we breaking our one-to-one if we end up deploying the app as a static in production?

@unruffledBeaver no, our approach for generating static sites in production should be separate from running Docker locally.

**Comment by unruffledBeaver** [comment]
@stevescavo I guess my point here is if we are building the site to be deployed in production statically, wouldnt it be better not to build it inside node locally? Maybe its not a huge deal but I feel like docker should be easy to remove all together if we know the app is going to be static and those who might want to use the starter that arent using our pipeline can simple dev and build a static app

**Comment by unruffledBeaver** [comment]
After discussing this with @rynocouse I changed my mind from my last comment and I see the advantage of always running docker for development, even if the site wont be deployed into a container. Mostly that any package that builds against a node target, like Node-Sass, will rely on local node instances which could very from host to host without freezing the version in docker.

**Pull request merged**
